# Generated by Django 4.2 on 2023-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_user_exp_alter_user_is_active_alter_user_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='life',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mana',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
