# Generated by Django 4.2 on 2023-04-28 13:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_user_exp_alter_user_is_active_alter_user_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('action_type', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('points', models.IntegerField()),
                ('success_rate', models.IntegerField()),
                ('exp_given', models.IntegerField()),
                ('exp_extra', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='life',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='mana',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='EventHistoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('succeed', models.BooleanField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.action')),
                ('user_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('user_transmitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmitter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
