# Generated by Django 4.2 on 2023-04-28 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_user_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 28, 13, 39, 23, 770145, tzinfo=datetime.timezone.utc)),
        ),
    ]
