# Generated by Django 4.2 on 2023-04-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_datetime_start', models.DateTimeField()),
                ('game_datetime_end', models.DateTimeField()),
            ],
        ),
    ]
