# Generated by Django 4.2 on 2023-04-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventHistoy',
            new_name='EventHistory',
        ),
    ]
