# Generated by Django 4.2 on 2023-05-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_eventhistoy_eventhistory'),
        ('game', '0010_user_activated'),
    ]

    operations = [
    ]
