# Generated by Django 4.2 on 2023-05-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_merge_20230503_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activated',
        ),
    ]
