# Generated by Django 4.2 on 2023-05-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoption',
            name='mins_between_turns',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
