# Generated by Django 4.2 on 2023-05-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_gameoption_mins_between_turns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoption',
            name='game_datetime_end',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gameoption',
            name='game_datetime_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gameoption',
            name='mins_between_turns',
            field=models.IntegerField(default=60),
        ),
    ]
