# Generated by Django 4.2 on 2023-05-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_gameoption_game_datetime_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoption',
            name='mins_between_turns',
            field=models.IntegerField(default=60),
        ),
    ]
