# Generated by Django 4.2 on 2023-05-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_gameoption_mins_between_turns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameoption',
            name='mins_between_turns',
            field=models.IntegerField(),
        ),
    ]
