# Generated by Django 4.2 on 2023-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_action_action_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('success_rate', models.IntegerField()),
                ('actual_roll', models.IntegerField()),
                ('success', models.BooleanField()),
            ],
        ),
    ]
