# Generated by Django 4.2 on 2023-05-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_statisticsuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsUser',
        ),
    ]
