# Generated by Django 4.2 on 2023-05-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_statisticsuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsuser',
            old_name='date',
            new_name='act_date',
        ),
        migrations.RenameField(
            model_name='statisticsuser',
            old_name='time',
            new_name='act_time',
        ),
    ]
