# Generated by Django 4.2 on 2023-05-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_rename_date_statisticsuser_act_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatisticsUser',
        ),
    ]
